# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Agent(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Agent - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'id': 'str',
            'last_check_in_time': 'int',
            'hostname': 'str',
            'customer_id': 'str',
            'last_known_error': 'str',
            'last_error_time': 'int',
            'last_error_event': 'Event',
            'time_drift': 'int',
            'bytes_left_for_buffer': 'int',
            'bytes_per_minute_for_buffer': 'int',
            'local_queue_size': 'int',
            'version': 'str',
            'ssh_agent': 'bool',
            'in_trash': 'bool',
            'ephemeral': 'bool',
            'deleted': 'bool'
        }

        self.attribute_map = {
            'name': 'name',
            'id': 'id',
            'last_check_in_time': 'lastCheckInTime',
            'hostname': 'hostname',
            'customer_id': 'customerId',
            'last_known_error': 'lastKnownError',
            'last_error_time': 'lastErrorTime',
            'last_error_event': 'lastErrorEvent',
            'time_drift': 'timeDrift',
            'bytes_left_for_buffer': 'bytesLeftForBuffer',
            'bytes_per_minute_for_buffer': 'bytesPerMinuteForBuffer',
            'local_queue_size': 'localQueueSize',
            'version': 'version',
            'ssh_agent': 'sshAgent',
            'in_trash': 'inTrash',
            'ephemeral': 'ephemeral',
            'deleted': 'deleted'
        }

        self._name = None
        self._id = None
        self._last_check_in_time = None
        self._hostname = None
        self._customer_id = None
        self._last_known_error = None
        self._last_error_time = None
        self._last_error_event = None
        self._time_drift = None
        self._bytes_left_for_buffer = None
        self._bytes_per_minute_for_buffer = None
        self._local_queue_size = None
        self._version = None
        self._ssh_agent = None
        self._in_trash = None
        self._ephemeral = None
        self._deleted = None

    @property
    def name(self):
        """
        Gets the name of this Agent.
        Agent name (modifiable)

        :return: The name of this Agent.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Agent.
        Agent name (modifiable)

        :param name: The name of this Agent.
        :type: str
        """
        self._name = name

    @property
    def id(self):
        """
        Gets the id of this Agent.


        :return: The id of this Agent.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Agent.


        :param id: The id of this Agent.
        :type: str
        """
        self._id = id

    @property
    def last_check_in_time(self):
        """
        Gets the last_check_in_time of this Agent.
        Last time when this agent checked in (in milliseconds since the unix epoch)

        :return: The last_check_in_time of this Agent.
        :rtype: int
        """
        return self._last_check_in_time

    @last_check_in_time.setter
    def last_check_in_time(self, last_check_in_time):
        """
        Sets the last_check_in_time of this Agent.
        Last time when this agent checked in (in milliseconds since the unix epoch)

        :param last_check_in_time: The last_check_in_time of this Agent.
        :type: int
        """
        self._last_check_in_time = last_check_in_time

    @property
    def hostname(self):
        """
        Gets the hostname of this Agent.
        Host name of the machine running the agent

        :return: The hostname of this Agent.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """
        Sets the hostname of this Agent.
        Host name of the machine running the agent

        :param hostname: The hostname of this Agent.
        :type: str
        """
        self._hostname = hostname

    @property
    def customer_id(self):
        """
        Gets the customer_id of this Agent.


        :return: The customer_id of this Agent.
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """
        Sets the customer_id of this Agent.


        :param customer_id: The customer_id of this Agent.
        :type: str
        """
        self._customer_id = customer_id

    @property
    def last_known_error(self):
        """
        Gets the last_known_error of this Agent.
        deprecated

        :return: The last_known_error of this Agent.
        :rtype: str
        """
        return self._last_known_error

    @last_known_error.setter
    def last_known_error(self, last_known_error):
        """
        Sets the last_known_error of this Agent.
        deprecated

        :param last_known_error: The last_known_error of this Agent.
        :type: str
        """
        self._last_known_error = last_known_error

    @property
    def last_error_time(self):
        """
        Gets the last_error_time of this Agent.
        deprecated

        :return: The last_error_time of this Agent.
        :rtype: int
        """
        return self._last_error_time

    @last_error_time.setter
    def last_error_time(self, last_error_time):
        """
        Sets the last_error_time of this Agent.
        deprecated

        :param last_error_time: The last_error_time of this Agent.
        :type: int
        """
        self._last_error_time = last_error_time

    @property
    def last_error_event(self):
        """
        Gets the last_error_event of this Agent.


        :return: The last_error_event of this Agent.
        :rtype: Event
        """
        return self._last_error_event

    @last_error_event.setter
    def last_error_event(self, last_error_event):
        """
        Sets the last_error_event of this Agent.


        :param last_error_event: The last_error_event of this Agent.
        :type: Event
        """
        self._last_error_event = last_error_event

    @property
    def time_drift(self):
        """
        Gets the time_drift of this Agent.
        Time drift of the agent's clock compared to Wavefront servers

        :return: The time_drift of this Agent.
        :rtype: int
        """
        return self._time_drift

    @time_drift.setter
    def time_drift(self, time_drift):
        """
        Sets the time_drift of this Agent.
        Time drift of the agent's clock compared to Wavefront servers

        :param time_drift: The time_drift of this Agent.
        :type: int
        """
        self._time_drift = time_drift

    @property
    def bytes_left_for_buffer(self):
        """
        Gets the bytes_left_for_buffer of this Agent.
        Number of bytes of space remaining in the persistent disk queue of this agent

        :return: The bytes_left_for_buffer of this Agent.
        :rtype: int
        """
        return self._bytes_left_for_buffer

    @bytes_left_for_buffer.setter
    def bytes_left_for_buffer(self, bytes_left_for_buffer):
        """
        Sets the bytes_left_for_buffer of this Agent.
        Number of bytes of space remaining in the persistent disk queue of this agent

        :param bytes_left_for_buffer: The bytes_left_for_buffer of this Agent.
        :type: int
        """
        self._bytes_left_for_buffer = bytes_left_for_buffer

    @property
    def bytes_per_minute_for_buffer(self):
        """
        Gets the bytes_per_minute_for_buffer of this Agent.
        Bytes used per minute by the persistent disk queue of this agent

        :return: The bytes_per_minute_for_buffer of this Agent.
        :rtype: int
        """
        return self._bytes_per_minute_for_buffer

    @bytes_per_minute_for_buffer.setter
    def bytes_per_minute_for_buffer(self, bytes_per_minute_for_buffer):
        """
        Sets the bytes_per_minute_for_buffer of this Agent.
        Bytes used per minute by the persistent disk queue of this agent

        :param bytes_per_minute_for_buffer: The bytes_per_minute_for_buffer of this Agent.
        :type: int
        """
        self._bytes_per_minute_for_buffer = bytes_per_minute_for_buffer

    @property
    def local_queue_size(self):
        """
        Gets the local_queue_size of this Agent.
        Number of items in the persistent disk queue of this agent

        :return: The local_queue_size of this Agent.
        :rtype: int
        """
        return self._local_queue_size

    @local_queue_size.setter
    def local_queue_size(self, local_queue_size):
        """
        Sets the local_queue_size of this Agent.
        Number of items in the persistent disk queue of this agent

        :param local_queue_size: The local_queue_size of this Agent.
        :type: int
        """
        self._local_queue_size = local_queue_size

    @property
    def version(self):
        """
        Gets the version of this Agent.


        :return: The version of this Agent.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this Agent.


        :param version: The version of this Agent.
        :type: str
        """
        self._version = version

    @property
    def ssh_agent(self):
        """
        Gets the ssh_agent of this Agent.
        deprecated

        :return: The ssh_agent of this Agent.
        :rtype: bool
        """
        return self._ssh_agent

    @ssh_agent.setter
    def ssh_agent(self, ssh_agent):
        """
        Sets the ssh_agent of this Agent.
        deprecated

        :param ssh_agent: The ssh_agent of this Agent.
        :type: bool
        """
        self._ssh_agent = ssh_agent

    @property
    def in_trash(self):
        """
        Gets the in_trash of this Agent.


        :return: The in_trash of this Agent.
        :rtype: bool
        """
        return self._in_trash

    @in_trash.setter
    def in_trash(self, in_trash):
        """
        Sets the in_trash of this Agent.


        :param in_trash: The in_trash of this Agent.
        :type: bool
        """
        self._in_trash = in_trash

    @property
    def ephemeral(self):
        """
        Gets the ephemeral of this Agent.
        When true, this agent is expected to be ephemeral (possibly hosted on a short-lived container) and will be deleted after a period of inactivity (not checking in)

        :return: The ephemeral of this Agent.
        :rtype: bool
        """
        return self._ephemeral

    @ephemeral.setter
    def ephemeral(self, ephemeral):
        """
        Sets the ephemeral of this Agent.
        When true, this agent is expected to be ephemeral (possibly hosted on a short-lived container) and will be deleted after a period of inactivity (not checking in)

        :param ephemeral: The ephemeral of this Agent.
        :type: bool
        """
        self._ephemeral = ephemeral

    @property
    def deleted(self):
        """
        Gets the deleted of this Agent.


        :return: The deleted of this Agent.
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted):
        """
        Sets the deleted of this Agent.


        :param deleted: The deleted of this Agent.
        :type: bool
        """
        self._deleted = deleted

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

