name: Prepare Package for Publishing on PyPI

on:
  workflow_call:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          check-latest: true
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -U build
      - name: Build Package
        run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1
