name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  prepare:
    uses: ./.github/workflows/package.yml
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish the Package
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
