name: Publish to PyPI

on:
  resease:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare the Package
      uses: ./.github/workflows/package.yml
    - name: Publish the Package
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
